### ISSUE TITLE
psAgemodel: erroneous peaks and troughs picked at beginning and end of data

### ISSUE THREAD

**Issue by ccasadio** [lawmana/coralPSM#2]
first and last couple of cycles worth of data have a few too many peaks and troughs

**Comment by lawmana** [comment]
The extra peaks and troughs are likely arising because of edge effects with the lowpass filter. https://github.com/lawmana/coralPSM/blob/70b472797888dde3c6dfd903fe6de5c3088edce5/psAgeModel.m#L179

**Comment by lawmana** [comment]
fixed in #4 
commit dc46b497a0680f1b71c52c8b817a8ff3ddd6f33a
